spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb+srv://fittracker_admin:h05RtNwGAw8v9xx3@fitness-cluster.41bmibj.mongodb.net/fitnessactivity?retryWrites=true&w=majority&appName=fitness-cluster
      database: fitnessactivity
  mongodb:
    uri: mongodb+srv://fittracker_admin:h05RtNwGAw8v9xx3@fitness-cluster.41bmibj.mongodb.net/fitnessactivity?retryWrites=true&w=majority&appName=fitness-cluster
    database: fitnessactivity

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking