server:
  port: 8083

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb+srv://fittracker_admin:h05RtNwGAw8v9xx3@fitness-cluster.41bmibj.mongodb.net/fitnessrecommendation?retryWrites=true&w=majority&appName=fitness-cluster
      database: fitnessrecommendation
  mongodb:
    uri: mongodb+srv://fittracker_admin:h05RtNwGAw8v9xx3@fitness-cluster.41bmibj.mongodb.net/fitnessrecommendation?retryWrites=true&w=majority&appName=fitness-cluster
    database: fitnessrecommendation

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

openrouter:
  api:
    url: ${OPENROUTER_API_URL:https://openrouter.ai/api/v1/chat/completions}
    key: ${OPENROUTER_API_KEY:}
    model: ${OPENROUTER_MODEL:openrouter/free}
